<script>
  import { createEventDispatcher } from "svelte";
  import AgencyRateScatter from "$lib/components/AgencyRateScatter.svelte";
  import {
    agency_yearly_data_heading,
    agency_scatter_total_stops_vs_citations_title,
    agency_scatter_nonwhite_stops_vs_citations_title,
    agency_scatter_white_stops_vs_citations_title,
    agency_scatter_total_stops_label,
    agency_scatter_total_stops_nonwhite_label,
    agency_scatter_total_stops_white_label,
    agency_scatter_citations_label,
    agency_scatter_citations_nonwhite_label,
    agency_scatter_citations_white_label,
    agency_scatter_min_citations_note,
    agency_scatter_min_citations_note_small,
    agency_scatter_citation_vs_arrest_heading,
    agency_scatter_citation_vs_arrest_nonwhite_heading,
    agency_scatter_citation_vs_arrest_white_heading,
    agency_scatter_citation_rate_label,
    agency_scatter_arrest_rate_label,
    agency_scatter_citation_rate_nonwhite_label,
    agency_scatter_arrest_rate_nonwhite_label,
    agency_scatter_citation_rate_white_label,
    agency_scatter_arrest_rate_white_label,
    agency_scatter_arrests_label,
    agency_scatter_arrests_nonwhite_label,
    agency_scatter_arrests_white_label,
    agency_scatter_search_vs_hit_heading,
    agency_scatter_search_vs_hit_nonwhite_heading,
    agency_scatter_search_vs_hit_white_heading,
    agency_scatter_search_rate_label,
    agency_scatter_search_rate_nonwhite_label,
    agency_scatter_search_rate_white_label,
    agency_scatter_hit_rate_label,
    agency_scatter_hit_rate_nonwhite_label,
    agency_scatter_hit_rate_white_label,
    agency_scatter_searches_label,
    agency_scatter_searches_nonwhite_label,
    agency_scatter_searches_white_label,
    agency_scatter_contraband_hits_label,
    agency_scatter_contraband_hits_nonwhite_label,
    agency_scatter_contraband_hits_white_label,
    agency_scatter_min_searches_note,
    agency_scatter_min_searches_note_small,
  } from "$lib/paraglide/messages";

  /** @type {string[]} */
  export let years = [];
  /** @type {string} */
  export let selectedYear = "";
  /** @type {string} */
  export let agencyName = "";
  /** @type {string[]} */
  export let excludeAgencies = [];
  /** @type {(value: number, opts?: { isMax: boolean }) => string} */
  export let formatPercentTick;

  const dispatch = createEventDispatcher();

  const onYearClick = (year) => dispatch("yearselect", { year, source: "bottom" });
</script>

<div class="mt-12">
  <div class="flex flex-col gap-3">
    <div
      role="tablist"
      aria-label={agency_yearly_data_heading()}
      class="mt-12 flex flex-wrap items-center gap-2"
    >
      {#each years as year}
        <button
          type="button"
          role="tab"
          aria-selected={year === selectedYear}
          class={`rounded-md border px-3 py-1.5 text-sm font-semibold tracking-wide transition sm:text-base ${
            year === selectedYear
              ? "border-slate-900 bg-slate-900 text-white"
              : "border-slate-200 bg-white text-slate-600 hover:border-slate-300 hover:text-slate-900"
          }`}
          on:click={() => onYearClick(year)}
        >
          {year}
        </button>
      {/each}
    </div>
    <div class="relative left-1/2 mt-4 w-screen -translate-x-1/2 space-y-4 px-4 sm:px-6">
      <div class="grid gap-7 lg:gap-8 lg:grid-cols-3">
        <AgencyRateScatter
          {selectedYear}
          {agencyName}
          title={agency_scatter_total_stops_vs_citations_title()}
          domainGroup="stops-citations"
          showMeanLines={true}
          xLabel={agency_scatter_total_stops_label()}
          yLabel={agency_scatter_citations_label()}
          xMetricKey="rates-by-race--totals--all-stops"
          yMetricKey="rates-by-race--totals--citations"
          excludeAgencies={excludeAgencies}
          minStops={500}
          sizeByStops={true}
          stopsLabel={agency_scatter_total_stops_label()}
          minCount={50}
          minCountKey="rates-by-race--totals--citations"
          minCountMessage={agency_scatter_min_citations_note()}
          note={agency_scatter_min_citations_note()}
          xScaleType="log"
          yScaleType="log"
          minX={1}
          minY={1}
        />
        <AgencyRateScatter
          {selectedYear}
          {agencyName}
          title={agency_scatter_nonwhite_stops_vs_citations_title()}
          domainGroup="stops-citations"
          showMeanLines={true}
          xLabel={agency_scatter_total_stops_nonwhite_label()}
          yLabel={agency_scatter_citations_nonwhite_label()}
          xMetricKey="rates-by-race--totals--all-stops"
          yMetricKey="rates-by-race--totals--citations"
          xColumn="Non-white"
          yColumn="Non-white"
          excludeAgencies={excludeAgencies}
          minStops={500}
          sizeByStops={true}
          stopsColumn="Non-white"
          stopsLabel={agency_scatter_total_stops_nonwhite_label()}
          minCount={25}
          minCountKey="rates-by-race--totals--citations"
          minCountColumn="Non-white"
          minCountMessage={agency_scatter_min_citations_note_small()}
          note={agency_scatter_min_citations_note_small()}
          xScaleType="log"
          yScaleType="log"
          minX={1}
          minY={1}
        />
        <AgencyRateScatter
          {selectedYear}
          {agencyName}
          title={agency_scatter_white_stops_vs_citations_title()}
          domainGroup="stops-citations"
          showMeanLines={true}
          xLabel={agency_scatter_total_stops_white_label()}
          yLabel={agency_scatter_citations_white_label()}
          xMetricKey="rates-by-race--totals--all-stops"
          yMetricKey="rates-by-race--totals--citations"
          xColumn="White"
          yColumn="White"
          excludeAgencies={excludeAgencies}
          minStops={500}
          sizeByStops={true}
          stopsColumn="White"
          stopsLabel={agency_scatter_total_stops_white_label()}
          minCount={25}
          minCountKey="rates-by-race--totals--citations"
          minCountColumn="White"
          minCountMessage={agency_scatter_min_citations_note_small()}
          note={agency_scatter_min_citations_note_small()}
          xScaleType="log"
          yScaleType="log"
          minX={1}
          minY={1}
        />
      </div>
      <div class="grid gap-7 lg:gap-8 lg:grid-cols-3">
        <AgencyRateScatter
          {selectedYear}
          {agencyName}
          title={agency_scatter_citation_vs_arrest_heading()}
          domainGroup="citation-arrest"
          showMeanLines={true}
          xLabel={agency_scatter_citation_rate_label()}
          yLabel={agency_scatter_arrest_rate_label()}
          xMetricKey="rates-by-race--totals--citations-rate"
          yMetricKey="rates-by-race--totals--arrests-rate"
          excludeAgencies={excludeAgencies}
          formatXAxisTick={formatPercentTick}
          formatYAxisTick={formatPercentTick}
          xCountKey="rates-by-race--totals--citations"
          yCountKey="rates-by-race--totals--arrests"
          xCountLabel={agency_scatter_citations_label()}
          yCountLabel={agency_scatter_arrests_label()}
          minStops={500}
          sizeByStops={true}
          stopsLabel={agency_scatter_total_stops_label()}
          minCount={50}
          minCountKey="rates-by-race--totals--citations"
          minCountMessage={agency_scatter_min_citations_note()}
          note={agency_scatter_min_citations_note()}
          excludeExactValue={100}
          minX={0}
          minY={0}
          maxX={100}
          maxY={100}
        />
        <AgencyRateScatter
          {selectedYear}
          {agencyName}
          title={agency_scatter_citation_vs_arrest_nonwhite_heading()}
          domainGroup="citation-arrest"
          showMeanLines={true}
          xLabel={agency_scatter_citation_rate_nonwhite_label()}
          yLabel={agency_scatter_arrest_rate_nonwhite_label()}
          xMetricKey="rates-by-race--totals--citations-rate"
          yMetricKey="rates-by-race--totals--arrests-rate"
          xColumn="Non-white"
          yColumn="Non-white"
          excludeAgencies={excludeAgencies}
          formatXAxisTick={formatPercentTick}
          formatYAxisTick={formatPercentTick}
          xCountKey="rates-by-race--totals--citations"
          yCountKey="rates-by-race--totals--arrests"
          xCountColumn="Non-white"
          yCountColumn="Non-white"
          xCountLabel={agency_scatter_citations_nonwhite_label()}
          yCountLabel={agency_scatter_arrests_nonwhite_label()}
          minStops={500}
          sizeByStops={true}
          stopsColumn="Non-white"
          stopsLabel={agency_scatter_total_stops_nonwhite_label()}
          minCount={25}
          minCountKey="rates-by-race--totals--citations"
          minCountColumn="Non-white"
          minCountMessage={agency_scatter_min_citations_note_small()}
          note={agency_scatter_min_citations_note_small()}
          excludeExactValue={100}
          minX={0}
          minY={0}
          maxX={100}
          maxY={100}
        />
        <AgencyRateScatter
          {selectedYear}
          {agencyName}
          title={agency_scatter_citation_vs_arrest_white_heading()}
          domainGroup="citation-arrest"
          showMeanLines={true}
          xLabel={agency_scatter_citation_rate_white_label()}
          yLabel={agency_scatter_arrest_rate_white_label()}
          xMetricKey="rates-by-race--totals--citations-rate"
          yMetricKey="rates-by-race--totals--arrests-rate"
          xColumn="White"
          yColumn="White"
          excludeAgencies={excludeAgencies}
          formatXAxisTick={formatPercentTick}
          formatYAxisTick={formatPercentTick}
          xCountKey="rates-by-race--totals--citations"
          yCountKey="rates-by-race--totals--arrests"
          xCountColumn="White"
          yCountColumn="White"
          xCountLabel={agency_scatter_citations_white_label()}
          yCountLabel={agency_scatter_arrests_white_label()}
          minStops={500}
          sizeByStops={true}
          stopsColumn="White"
          stopsLabel={agency_scatter_total_stops_white_label()}
          minCount={25}
          minCountKey="rates-by-race--totals--citations"
          minCountColumn="White"
          minCountMessage={agency_scatter_min_citations_note_small()}
          note={agency_scatter_min_citations_note_small()}
          excludeExactValue={100}
          minX={0}
          minY={0}
          maxX={100}
          maxY={100}
        />
      </div>
      <div class="grid gap-7 lg:gap-8 lg:grid-cols-3">
        <AgencyRateScatter
          {selectedYear}
          {agencyName}
          title={agency_scatter_search_vs_hit_heading()}
          domainGroup="hits-searches"
          showMeanLines={true}
          xLabel={agency_scatter_search_rate_label()}
          yLabel={agency_scatter_hit_rate_label()}
          xMetricKey="rates-by-race--totals--searches-rate"
          yMetricKey="rates-by-race--totals--contraband-hit-rate"
          formatXAxisTick={formatPercentTick}
          formatYAxisTick={formatPercentTick}
          xCountKey="rates-by-race--totals--searches"
          yCountKey="rates-by-race--totals--contraband"
          xCountLabel={agency_scatter_searches_label()}
          yCountLabel={agency_scatter_contraband_hits_label()}
          excludeAgencies={excludeAgencies}
          minStops={500}
          sizeByStops={true}
          stopsLabel={agency_scatter_total_stops_label()}
          minCount={25}
          minCountKey="rates-by-race--totals--searches"
          excludeAboveX={50}
          minCountMessage={agency_scatter_min_searches_note()}
          note={agency_scatter_min_searches_note()}
        />
        <AgencyRateScatter
          {selectedYear}
          {agencyName}
          title={agency_scatter_search_vs_hit_nonwhite_heading()}
          domainGroup="hits-searches"
          showMeanLines={true}
          xLabel={agency_scatter_search_rate_nonwhite_label()}
          yLabel={agency_scatter_hit_rate_nonwhite_label()}
          xMetricKey="rates-by-race--totals--searches-rate"
          yMetricKey="rates-by-race--totals--contraband-hit-rate"
          xColumn="Non-white"
          yColumn="Non-white"
          formatXAxisTick={formatPercentTick}
          formatYAxisTick={formatPercentTick}
          xCountKey="rates-by-race--totals--searches"
          yCountKey="rates-by-race--totals--contraband"
          xCountColumn="Non-white"
          yCountColumn="Non-white"
          xCountLabel={agency_scatter_searches_nonwhite_label()}
          yCountLabel={agency_scatter_contraband_hits_nonwhite_label()}
          excludeAgencies={excludeAgencies}
          minStops={500}
          sizeByStops={true}
          stopsColumn="Non-white"
          stopsLabel={agency_scatter_total_stops_nonwhite_label()}
          minCount={25}
          minCountKey="rates-by-race--totals--searches"
          minCountColumn="Non-white"
          excludeAboveX={50}
          minCountMessage={agency_scatter_min_searches_note_small()}
          note={agency_scatter_min_searches_note_small()}
        />
        <AgencyRateScatter
          {selectedYear}
          {agencyName}
          title={agency_scatter_search_vs_hit_white_heading()}
          domainGroup="hits-searches"
          showMeanLines={true}
          xLabel={agency_scatter_search_rate_white_label()}
          yLabel={agency_scatter_hit_rate_white_label()}
          xMetricKey="rates-by-race--totals--searches-rate"
          yMetricKey="rates-by-race--totals--contraband-hit-rate"
          xColumn="White"
          yColumn="White"
          formatXAxisTick={formatPercentTick}
          formatYAxisTick={formatPercentTick}
          xCountKey="rates-by-race--totals--searches"
          yCountKey="rates-by-race--totals--contraband"
          xCountColumn="White"
          yCountColumn="White"
          xCountLabel={agency_scatter_searches_white_label()}
          yCountLabel={agency_scatter_contraband_hits_white_label()}
          excludeAgencies={excludeAgencies}
          minStops={500}
          sizeByStops={true}
          stopsColumn="White"
          stopsLabel={agency_scatter_total_stops_white_label()}
          minCount={25}
          minCountKey="rates-by-race--totals--searches"
          minCountColumn="White"
          excludeAboveX={50}
          minCountMessage={agency_scatter_min_searches_note_small()}
          note={agency_scatter_min_searches_note_small()}
        />
      </div>
    </div>
  </div>
</div>
